/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import comun.ConversorStringDate;
import comun.InicializarCombo;
import comun.MostrarMensaje;
import comun.Redondear;
import controlador.ExpertoCrearExcel;
import controlador.ExpertoImputacion;
import dto.DtoImputacionCheque;
import dto.DtoImputacionMovimiento;
import dto.DtoResultadoConsulta;
import dto.DtoVendedor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maquina0
 */
public class PantallaImputacionesCheques extends javax.swing.JFrame {

    private Calendar calendar;
    private ExpertoImputacion expertoImputacion;
    private ExpertoCrearExcel expertoCrearExcel;
    private DtoResultadoConsulta consulta;
    //List<DtoImputacionCheque> imputaciones = new ArrayList<>();
    List<DtoVendedor> vendedores = new ArrayList<>();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaImputacionesCheques() {
        initComponents();
        this.setLocationRelativeTo(null);
        expertoImputacion = new ExpertoImputacion();
        expertoCrearExcel = new ExpertoCrearExcel();
        //mostrarBasesDatos(); SE ELIMINO EL COMBO!
        mostrarVendedores();
        this.calendar = Calendar.getInstance();
        crearAnioDesde(calendar.get(Calendar.YEAR));
        crearAnioHasta(calendar.get(Calendar.YEAR));
        crearMesDesde((calendar.get(Calendar.MONTH) + 1));
        crearMesHasta((calendar.get(Calendar.MONTH) + 1));
        crearDiaDesde(calendar.get(Calendar.DATE), comboMesDesde.getSelectedIndex());
        crearDiaHasta(calendar.get(Calendar.DATE), comboMesDesde.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboDiaDesde = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboMesDesde = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboAnioDesde = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        comboDiaHasta = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboMesHasta = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        comboAnioHasta = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboVendedores = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaImputaciones = new javax.swing.JTable();
        excel = new javax.swing.JButton();
        consultarCheques = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Fechas de coonsulta:");

        jLabel3.setText("Fecha desde:");

        comboDiaDesde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDiaDesde.setNextFocusableComponent(comboAnioDesde);

        jLabel4.setText("/");

        comboMesDesde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMesDesde.setNextFocusableComponent(comboDiaDesde);
        comboMesDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesDesdeActionPerformed(evt);
            }
        });

        jLabel5.setText("/");

        comboAnioDesde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Fecha hasta:");

        comboDiaHasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDiaHasta.setNextFocusableComponent(comboAnioHasta);

        jLabel7.setText("/");

        comboMesHasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMesHasta.setNextFocusableComponent(comboDiaHasta);
        comboMesHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesHastaActionPerformed(evt);
            }
        });

        jLabel8.setText("/");

        comboAnioHasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Vendedores:");

        comboVendedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVendedoresActionPerformed(evt);
            }
        });

        tablaImputaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Cliente", "Vendedor", "Recibo N°", "Fecha Recibo", "Importe Recibo", "Factura N°", "Fecha Emis Fact", "Importe Factura", "Cheque N°", "Importe Cheque", "Fecha Emis Chq", "Fecha Cob Chq", "Dif Fac Rec", "Dif Fac Chq"
            }
        ));
        jScrollPane1.setViewportView(tablaImputaciones);

        excel.setText("Generar Excel");
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });

        consultarCheques.setText("Consultar Imputaciones con Cheques");
        consultarCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarChequesActionPerformed(evt);
            }
        });

        jLabel10.setText("Importe Total:");

        jLabel11.setText("..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarCheques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboVendedores, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboDiaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboMesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboAnioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboDiaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboMesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboAnioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDiaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboMesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboAnioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboDiaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboMesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(comboAnioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarCheques))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMesDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesDesdeActionPerformed
        // TODO add your handling code here:
        crearDiaDesde(calendar.get(Calendar.DATE), comboMesDesde.getSelectedIndex());
    }//GEN-LAST:event_comboMesDesdeActionPerformed

    private void comboMesHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesHastaActionPerformed
        // TODO add your handling code here:
        crearDiaHasta(calendar.get(Calendar.DATE), comboMesDesde.getSelectedIndex());
    }//GEN-LAST:event_comboMesHastaActionPerformed

    private void comboVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVendedoresActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        if (!consulta.getImputacionesCheque().isEmpty()) {
            try {
                String fechaDesde, fechaHasta, desde, hasta;
                fechaDesde = comboAnioDesde.getSelectedItem().toString() + "-" + comboMesDesde.getSelectedItem().toString() + "-" + comboDiaDesde.getSelectedItem().toString();
                fechaHasta = comboAnioHasta.getSelectedItem().toString() + "-" + comboMesHasta.getSelectedItem().toString() + "-" + comboDiaHasta.getSelectedItem().toString();
                desde = ConversorStringDate.formatearFecha(fechaDesde);
                hasta = ConversorStringDate.formatearFecha(fechaHasta);
                expertoCrearExcel.crearExcelCheques(consulta.getImputacionesCheque(), fechaDesde, fechaHasta);
                MostrarMensaje.mostrarMensaje("Archivo creado con exito", new ArrayList<JFrame>());
            } catch (IOException ex) {
                MostrarMensaje.mostrarMensaje("Hubo un error al crear archivo", new ArrayList<JFrame>());
            }
        } else {
            MostrarMensaje.mostrarMensaje("Por favor, realice una consulta de remitos", new ArrayList<JFrame>());
        }
    }//GEN-LAST:event_excelActionPerformed

    private void consultarChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarChequesActionPerformed
        String fechaDesde, fechaHasta, vendedor;
        fechaDesde = comboAnioDesde.getSelectedItem().toString() + comboMesDesde.getSelectedItem().toString() + comboDiaDesde.getSelectedItem().toString();
        fechaHasta = comboAnioHasta.getSelectedItem().toString() + comboMesHasta.getSelectedItem().toString() + comboDiaHasta.getSelectedItem().toString();
        vendedor = comboVendedores.getSelectedItem().toString();
        System.out.println(fechaDesde);
        System.out.println(fechaHasta);
        if (comboVendedores.getSelectedItem().toString().equals("TODOS")) {
            cargarImputaciones(fechaDesde, fechaHasta);
        } else {
            cargarImputacionesVendedor(expertoImputacion.obtenerCodVendedor(vendedor), fechaDesde, fechaHasta);
        }
    }//GEN-LAST:event_consultarChequesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboAnioDesde;
    private javax.swing.JComboBox comboAnioHasta;
    private javax.swing.JComboBox comboDiaDesde;
    private javax.swing.JComboBox comboDiaHasta;
    private javax.swing.JComboBox comboMesDesde;
    private javax.swing.JComboBox comboMesHasta;
    private javax.swing.JComboBox comboVendedores;
    private javax.swing.JButton consultarCheques;
    private javax.swing.JButton excel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaImputaciones;
    // End of variables declaration//GEN-END:variables

    private void crearAnioDesde(int anio) {
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        defaultComboBoxModel.addElement(anio - 2);
        defaultComboBoxModel.addElement(anio - 1);
        defaultComboBoxModel.addElement(anio);
        defaultComboBoxModel.addElement(anio + 1);
        defaultComboBoxModel.addElement(anio + 2);
        defaultComboBoxModel.setSelectedItem(anio);
        comboAnioDesde.setModel(defaultComboBoxModel);
    }

    private void crearAnioHasta(int anio) {
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        defaultComboBoxModel.addElement(anio - 2);
        defaultComboBoxModel.addElement(anio - 1);
        defaultComboBoxModel.addElement(anio);
        defaultComboBoxModel.addElement(anio + 1);
        defaultComboBoxModel.addElement(anio + 2);
        defaultComboBoxModel.setSelectedItem(anio);
        comboAnioHasta.setModel(defaultComboBoxModel);
    }

    private void crearMesDesde(int mes) {
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        for (int recorrido = 1; recorrido < 13; recorrido++) {
            if (recorrido < 10) {
                defaultComboBoxModel.addElement("0" + recorrido);
            } else {
                defaultComboBoxModel.addElement(recorrido);
            }
        }
        if (mes < 10) {
            defaultComboBoxModel.setSelectedItem("0" + mes);
        } else {
            defaultComboBoxModel.setSelectedItem(mes);
        }
        comboMesDesde.setModel(defaultComboBoxModel);
    }

    private void crearMesHasta(int mes) {
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        for (int recorrido = 1; recorrido < 13; recorrido++) {
            if (recorrido < 10) {
                defaultComboBoxModel.addElement("0" + recorrido);
            } else {
                defaultComboBoxModel.addElement(recorrido);
            }
        }
        if (mes < 10) {
            defaultComboBoxModel.setSelectedItem("0" + mes);
        } else {
            defaultComboBoxModel.setSelectedItem(mes);
        }
        comboMesHasta.setModel(defaultComboBoxModel);
    }

    private void crearDiaDesde(int dia, int mes) {
        int maxDia;
        switch (mes) {
            case 0:
            case 2:
            case 4:
            case 6:
            case 7:
            case 9:
            case 11:
                maxDia = 31;
                break;
            case 3:
            case 5:
            case 8:
            case 10:
                maxDia = 30;
                break;
            case 1:
                int anio = Integer.valueOf(comboAnioDesde.getSelectedItem().toString());
                if (((anio % 4 == 0)
                        && !(anio % 100 == 0))
                        || (anio % 400 == 0)) {
                    maxDia = 29;
                } else {
                    maxDia = 28;
                }
                break;
            default:
                maxDia = 31;
        }
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        for (int recorrido = 1; recorrido <= maxDia; recorrido++) {
            if (recorrido < 10) {
                defaultComboBoxModel.addElement("0" + recorrido);
            } else {
                defaultComboBoxModel.addElement(recorrido);
            }
        }
        if (dia < 10) {
            defaultComboBoxModel.setSelectedItem("0" + dia);
        } else {
            defaultComboBoxModel.setSelectedItem(dia);
        }
        comboDiaDesde.setModel(defaultComboBoxModel);

    }

    private void crearDiaHasta(int dia, int mes) {
        int maxDia;
        switch (mes) {
            case 0:
            case 2:
            case 4:
            case 6:
            case 7:
            case 9:
            case 11:
                maxDia = 31;
                break;
            case 3:
            case 5:
            case 8:
            case 10:
                maxDia = 30;
                break;
            case 1:
                int anio = Integer.valueOf(comboAnioHasta.getSelectedItem().toString());
                if (((anio % 4 == 0)
                        && !(anio % 100 == 0))
                        || (anio % 400 == 0)) {
                    maxDia = 29;
                } else {
                    maxDia = 28;
                }
                break;
            default:
                maxDia = 31;
        }
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        for (int recorrido = 1; recorrido <= maxDia; recorrido++) {
            if (recorrido < 10) {
                defaultComboBoxModel.addElement("0" + recorrido);
            } else {
                defaultComboBoxModel.addElement(recorrido);
            }
        }
        if (dia < 10) {
            defaultComboBoxModel.setSelectedItem("0" + dia);
        } else {
            defaultComboBoxModel.setSelectedItem(dia);
        }
        comboDiaHasta.setModel(defaultComboBoxModel);
    }

    /*private void mostrarBasesDatos() {
        DefaultComboBoxModel defaultComboBoxModel = InicializarCombo.inicializarCombo(new DefaultComboBoxModel(), "Seleccione Empresa.");
        for (String base : expertoImputacion.buscarBasesDatos()) {
            defaultComboBoxModel.addElement(base);
        }
        comboBase.setModel(defaultComboBoxModel);
    }*/

    private void mostrarVendedores(){
        DefaultComboBoxModel defaultComboBoxModel = InicializarCombo.inicializarCombo(new DefaultComboBoxModel(), "TODOS");
        vendedores = expertoImputacion.obtenerVendedores();
        for (DtoVendedor vendedor : vendedores) {
            defaultComboBoxModel.addElement(vendedor.getNombreVendedor());
        }
        comboVendedores.setModel(defaultComboBoxModel);
    }
    private void cargarVendedores(String empresa) {
        DefaultComboBoxModel defaultComboBoxModel = InicializarCombo.inicializarCombo(new DefaultComboBoxModel(), "TODOS");
        vendedores = expertoImputacion.obtenerVendedores(empresa);
        for (DtoVendedor vendedor : vendedores) {
            defaultComboBoxModel.addElement(vendedor.getNombreVendedor());
        }
        comboVendedores.setModel(defaultComboBoxModel);
    }

    private void cargarImputacionesVendedor(String codVendedor, String fechaDesde, String fechaHasta) {
        consulta = expertoImputacion.obtenerImputacionesChequeVendedor(codVendedor, fechaDesde, fechaHasta);
        cargarTabla(consulta);
    }

    private void cargarImputaciones(String fechaDesde, String fechaHasta) {
        consulta = expertoImputacion.obtenerImputacionesCheque(fechaDesde, fechaHasta);
        cargarTabla(consulta);
    }

    private void cargarTabla(DtoResultadoConsulta resultado) {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Empresa");
        defaultTableModel.addColumn("Cliente");
        defaultTableModel.addColumn("Vendedor");
        defaultTableModel.addColumn("Recibo N°");
        defaultTableModel.addColumn("Fecha Recibo");
        defaultTableModel.addColumn("Importe Recibo");
        defaultTableModel.addColumn("Factura N°");
        defaultTableModel.addColumn("Fecha Emis Fact");
        defaultTableModel.addColumn("Importe Factura");
        defaultTableModel.addColumn("Cheque N°");
        defaultTableModel.addColumn("Importe Cheque");
        defaultTableModel.addColumn("Fecha Emis Chq");
        defaultTableModel.addColumn("Fecha Cob Chq");
        defaultTableModel.addColumn("Dif Fac Rec");
        defaultTableModel.addColumn("Pond Dif Rec");
        defaultTableModel.addColumn("Dif Fac Chq");
        defaultTableModel.addColumn("Pond Dif Chq");
        for (DtoImputacionCheque imputacion : resultado.getImputacionesCheque()) {
            Object[] fila = new Object[17];
            fila[0] = imputacion.getEmpresa();
            fila[1] = imputacion.getRazonSocial();
            fila[2] = imputacion.getNombreVendedor();
            fila[3] = imputacion.getNroRecibo();
            fila[4] = imputacion.getFechaRecibo();
            fila[5] = imputacion.getImporteRecibo();
            fila[6] = imputacion.getNroFactura();
            fila[7] = imputacion.getFechaEmisionFactura();
            fila[8] = imputacion.getImporteFactura();
            fila[9] = imputacion.getNroCheque();
            fila[10] = imputacion.getImporteCheque();
            fila[11] = imputacion.getFechaEmisCheque();
            fila[12] = imputacion.getFechaCobroCheque();
            fila[13] = imputacion.getDiferenciaFacRec();
            fila[14] = Redondear.redondear(Double.valueOf(imputacion.getPonderacionDifFacRec()), 2);
            fila[15] = imputacion.getDiferenciaFacChq();
            fila[16] = imputacion.getPonderacionDifFacChq() != null ? Redondear.redondear(Double.valueOf(imputacion.getPonderacionDifFacChq()), 2) : "";
            defaultTableModel.addRow(fila);
        }
        jLabel11.setText(String.valueOf(resultado.getTotal()));
        tablaImputaciones.setModel(defaultTableModel);
    }

}
